/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EDD.Lista;
import Funciones.Funcion;
import static Interfaces.Cargar.redApp;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Moises Liota
 */
public class Sucursales extends javax.swing.JFrame {

    DefaultComboBoxModel modeloSinSucursal = new DefaultComboBoxModel();
    DefaultComboBoxModel modeloConSucursal = new DefaultComboBoxModel();

    private Funcion func = new Funcion();

    public Sucursales() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        this.llenarComboBoxSinSucursal();
        this.llenarComboBoxConSucursal();

    }

    private void llenarComboBoxSinSucursal() {
        modeloSinSucursal.removeAllElements();
        Lista nombresSinSucursal = func.estacionesSinSucursal(redApp);
        if (!nombresSinSucursal.isEmpty()) {
            for (int i = 0; i < nombresSinSucursal.getSize(); i++) {
                String nombreActual = (String) nombresSinSucursal.getValor(i);
                modeloSinSucursal.addElement(nombreActual);
            }
        }

    }

    private void llenarComboBoxConSucursal() {
        modeloConSucursal.removeAllElements();
        Lista nombresConSucursal = func.estacionesConnSucursal(redApp);

        if (!nombresConSucursal.isEmpty()) {
            for (int i = 0; i < nombresConSucursal.getSize(); i++) {
                String nombreActual = (String) nombresConSucursal.getValor(i);
                modeloConSucursal.addElement(nombreActual);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estacionesSinSucursal = new javax.swing.JComboBox<>();
        volver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        aggSucursal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        estacionesConSucursal = new javax.swing.JComboBox<>();
        eliminarSucursal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Gestion de Sucursales");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel2.setText("Selecciona la estacion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        estacionesSinSucursal.setModel(modeloSinSucursal);
        jPanel1.add(estacionesSinSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 260, -1));

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Eliminar Sucursal en la Red");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        aggSucursal.setText("agregar sucursal");
        aggSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(aggSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 260, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Agregar Sucursal en la Red");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabel5.setText("Selecciona la estacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        estacionesConSucursal.setModel(modeloConSucursal);
        jPanel1.add(estacionesConSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 250, -1));

        eliminarSucursal.setText("eliminar sucursal");
        eliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Menu menu = new Menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void aggSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggSucursalActionPerformed
        String nombreEstacion = (String) estacionesSinSucursal.getSelectedItem();
        func.agregarSucursal(redApp, nombreEstacion);
        this.llenarComboBoxSinSucursal();
        this.llenarComboBoxConSucursal();
    }//GEN-LAST:event_aggSucursalActionPerformed

    private void eliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarSucursalActionPerformed
        String nombreEstacion = (String) estacionesConSucursal.getSelectedItem();
        func.eliminarSucursal(redApp, nombreEstacion);
        this.llenarComboBoxSinSucursal();
        this.llenarComboBoxConSucursal();
    }//GEN-LAST:event_eliminarSucursalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sucursales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aggSucursal;
    private javax.swing.JButton eliminarSucursal;
    private javax.swing.JComboBox<String> estacionesConSucursal;
    private javax.swing.JComboBox<String> estacionesSinSucursal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
